version: '3'

services:

  khanacademy-content-crawler:
    image: khanacademy-content-crawler:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/app
    command: npm run debug

  